datasets:
  # - root: data/more-data/LibriTTS
  #   source: LibriTTS
  #   languages: [EN]
  #   extension: .normalized.txt
  #   # This controls the grouping of the dataset (i.e. speaker)
  #   # 1 means we use the parent folder of the file as the group name
  #   group_parent_level: [2, 1]
  # - root: data/more-data/LibriTTS/test-clean/
  #   source: LibriTTS
  #   languages: [EN]
  #   extension: .normalized.txt
  #   group_parent_level: [2, 1]
  # - root: data/more-data/LibriTTS/test-other/
  #   source: LibriTTS
  #   languages: [EN]
  #   extension: .normalized.txt
  #   group_parent_level: [2, 1]
  - root: data/gigaspeech
    source: GigaSpeech
    languages: [EN]
    extension: .txt
    group_parent_level: [3,2,1]
