name: build-windows-package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/checkout@v4
        with:
          path: ./fish-speech
      - run: pip3 install huggingface-hub
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli download fishaudio/fish-speech-1 fish-speech-v1.0.zip \
          --local-dir ./ --local-dir-use-symlinks False
          unzip fish-speech-v1.0.zip -d fish-speech-zip
          mv fish-speech-zip/fish-speech/fishenv fish-speech-zip/fish-speech/ffmpeg.exe ./fish-speech
      - uses: actions/upload-artifact@v4
        with:
          name: fish-speech-main-${{ github.run_id }}
          path: ./fish-speech
